name: Build and Push Migrator Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    # types: [closed]
    # branches:
    #   - main
    # paths:
    #   - 'Dockerfile.migrator'
    #   - 'prisma/**'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  MIGRATOR_IMAGE_NAME: mcesarczyk/timely-api-standalone-migrator
  MIGRATOR_DOCKERHUB_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/timely-api-standalone-migrator

jobs:
  build_on_merge:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.MIGRATOR_IMAGE_NAME }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: 'image=moby/buildkit:v0.11.6'

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile.migrator
          push: true
          tags: |
            ${{ env.MIGRATOR_DOCKERHUB_IMAGE }}:latest
            ${{ env.MIGRATOR_DOCKERHUB_IMAGE }}:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ env.MIGRATOR_IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.MIGRATOR_IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: true
          sbom: true

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.MIGRATOR_IMAGE_NAME }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
